from flask import Flask, request, jsonify
from pylatex import Document, Section
import base64
import tempfile
import os

app = Flask(__name__)

@app.route("/")
def home():
    return "🚀 Welcome to the LaTeX API. Use POST /latex with JSON to compile LaTeX."

@app.route("/latex", methods=["POST"])
def compile_latex():
    try:
        data = request.get_json()
        text = data.get("text", "Hello World")

        # توليد مستند LaTeX بسيط
        doc = Document()
        with doc.create(Section("Generated by pylatex")):
            doc.append(text)

        # حفظ PDF مؤقت
        with tempfile.TemporaryDirectory() as tmpdir:
            tex_path = os.path.join(tmpdir, "doc")
            doc.generate_pdf(tex_path, clean_tex=False)

            with open(tex_path + ".pdf", "rb") as f:
                encoded_pdf = base64.b64encode(f.read()).decode("utf-8")

        return jsonify({"pdf_base64": encoded_pdf})

    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
